import { MD3LightTheme } from 'react-native-paper';

export const LightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#36693D',
    surfaceTint: '#36693D',
    onPrimary: '#FFFFFF',
    primaryContainer: '#B8F1B9',
    onPrimaryContainer: '#1D5128',
    secondary: '#516351',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#D4E8D1',
    onSecondaryContainer: '#3A4B3A',
    tertiary: '#39656C',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#BDEAF3',
    onTertiaryContainer: '#1F4D54',
    error: '#BA1A1A',
    onError: '#FFFFFF',
    errorContainer: '#FFDAD6',
    onErrorContainer: '#93000A',
    background: '#F7FBF2',
    onBackground: '#181D18',
    surface: '#F7FBF2',
    onSurface: '#181D18',
    surfaceVariant: '#DDE5D9',
    onSurfaceVariant: '#424940',
    outline: '#727970',
    outlineVariant: '#C1C9BE',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#2D322C',
    inverseOnSurface: '#EEF2E9',
    inversePrimary: '#9CD49F',
    primaryFixed: '#B8F1B9',
    onPrimaryFixed: '#002108',
    primaryFixedDim: '#9CD49F',
    onPrimaryFixedVariant: '#1D5128',
    secondaryFixed: '#D4E8D1',
    onSecondaryFixed: '#0F1F11',
    secondaryFixedDim: '#B8CCB5',
    onSecondaryFixedVariant: '#3A4B3A',
    tertiaryFixed: '#BDEAF3',
    onTertiaryFixed: '#001F24',
    tertiaryFixedDim: '#A1CED6',
    onTertiaryFixedVariant: '#1F4D54',
    surfaceDim: '#D7DBD3',
    surfaceBright: '#F7FBF2',
    surfaceContainerLowest: '#FFFFFF',
    surfaceContainerLow: '#F1F5EC',
    surfaceContainer: '#EBEFE7',
    surfaceContainerHigh: '#E5E9E1',
    surfaceContainerHighest: '#E0E4DB',
  },
};
